---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: decapod-argo-cd
    name: argo-cd
  name: argo-cd
spec:
  chart:
    type: git
    repository: https://github.com/argoproj/argo-helm.git
    name: charts/argo-cd
    version: master
  helmVersion: v3
  releaseName: argo-cd
  targetNamespace: argo
  values:
    installCRDs: false
    controller.replicas: 1
    repoServer.replicas: 1
    server.replicas: 1
    server.service.type: NodePort
    server.config:
      accounts.admin: "apiKey, login"
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: decapod-argo-events
    name: argo-events
  name: argo-events
spec:
  chart:
    type: git
    repository: https://github.com/argoproj/argo-helm.git
    name: charts/argo-events
    version: master
  helmVersion: v3
  releaseName: argo-events
  targetNamespace: argo
  values:
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: decapod-argo-rollouts
    name: argo-rollouts
  name: argo-rollouts
spec:
  chart:
    type: git
    repository: https://github.com/argoproj/argo-helm.git
    name: charts/argo-rollouts
    version: master
  helmVersion: v3
  releaseName: argo-rollouts
  targetNamespace: argo
  values:
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: decapod-argo-workflows
    name: argo-workflows
  name: argo-workflows
spec:
  chart:
    type: git
    repository: https://github.com/argoproj/argo-helm.git
    name: charts/argo-workflows
    version: master
  helmVersion: v3
  releaseName: argo-workflows
  targetNamespace: argo
  values:
    workflowArchive.enabled: true
    mysql.enabled: true
    nodeSelector:
      taco-lma: enabled
    mysql.persistence.storageClass: rbd
    mysql.persistence.size: 1GB
    mysql.nodeSelector:
      taco-lma: enabled
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: decapod-argo-applicationset
    name: argo-applicationset
  name: argo-applicationset
spec:
  chart:
    type: git
    repository: https://github.com/argoproj/argo-helm.git
    name: charts/argo-applicationset
    version: master
  helmVersion: v3
  releaseName: argo-applicationset
  targetNamespace: argo
  values:
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: decapod-argo-notifications
    name: argo-notifications
  name: argo-notifications
spec:
  chart:
    type: git
    repository: https://github.com/argoproj/argo-helm.git
    name: charts/argo-notifications
    version: master
  helmVersion: v3
  releaseName: argo-notifications
  targetNamespace: argo
  values:
  wait: true
