version: argoproj.io/v1alpha1
metadata:
  name: config-zero
  simultaneous: true
  checkInterval: 20
workflow:
  lma:
    1:
    - prometheus-operator
    - eck-operator
    - fluentbit-operator
    2:
    - eck-resource
    - prometheus
    - kube-state-metrics
    - prometheus-process-exporter
    - prometheus-pushgateway
    - prometheus-node-exporter
    - prometheus-adapter
    - addons
    3:
    - prometheus-fed-master
    - fluentbit
    - fed-addons
    - grafana
  lma_alone:
    1:
    - prometheus-operator
    - elasticsearch-operator
    - fluentbit-operator
    2:
    - elasticsearch-kibana
    - prometheus
    - kube-state-metrics
    - prometheus-process-exporter
    - prometheus-pushgateway
    - prometheus-node-exporter
    - prometheus-adapter
    - addons
    3:
    - prometheus-fed-master
    - fluentbit
    - fed-addons
    - grafana
  cloudconsole:

  default:
    1:
    - prometheus-operator
    - eck-operator
    - fluentbit-operator
    2:
    - eck-resource
    - prometheus
    - kube-state-metrics
    - prometheus-process-exporter
    - prometheus-pushgateway
    - prometheus-node-exporter
    - prometheus-adapter
    - addons
    - thanos-config
    - thanos
    3:
    - fluentbit
    - fed-addons
    - grafana
  openstack:
    0:
    - ingress
    - memcached
    - rabbitmq
    - mariadb
    - ceph-provisioners
    1:
    - keystone
    - glance
    - cinder
    2:
    - libvirt
    - openvswitch
    - nova
    - neutron
    3:
    - horizon
    - heat    
  servicemesh:
    1:
    - istio-operator
    - jaeger-operator
    2:
    - kiali-operator
    - service-mesh-controlplane
    - service-mesh-gateway
  argo:
    1:
    - argo-cd
    # - argo-events
    - argo-rollouts
    - argo-workflows
    # - argo-applicationset
    # - argo-notifications
  test:
    1:
      - istio-operator
    2: 
      - eck-operator
