apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: istio-operator
  name: istio-operator
spec:
  chart:
    name: istio-operator
    repository: https://openinfradev.github.io/hanu-helm-repo
    version: 1.7.0
  helmVersion: v3
  releaseName: istio-operator
  targetNamespace: istio-operator
  values:
    operatorNamespace: istio-system
    watchedNamespace: istio-system
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator
spec:
  chart:
    name: jaeger-operator
    repository: https://jaegertracing.github.io/helm-charts
    version: 2.19.1
  helmVersion: v3
  releaseName: jaeger-operator
  targetNamespace: lma
  values:
    jaeger:
      create: true
      namespace: lma
      nodeSelector: {}
      spec:
        agent:
          strategy: Sidecar
        collector:
          maxReplicas: 5
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
        storage:
          esIndexCleaner:
            enabled: true
            numberOfDays: 7
            schedule: 55 04 * * *
          options:
            es:
              index-prefix: jaeger
              password: tacoword
              server-urls: https://eck-elasticsearch-es-http:9200
              tls.ca: /etc/ssl/certs/tls.crt
              username: elastic
          type: elasticsearch
        strategy: production
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: es-tls
        volumes:
        - name: es-tls
          secret:
            secretName: eck-elasticsearch-es-http-certs-public
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: kiali-operator
  name: kiali-operator
spec:
  chart:
    name: kiali-operator
    repository: https://kiali.org/helm-charts
    version: 1.30.0
  helmVersion: v3
  releaseName: kiali-operator
  targetNamespace: istio-system
  values:
    cr:
      create: true
      name: kiali
      spec:
        auth:
          strategy: anonymous
        deployment:
          accessible_namespaces:
          - '**'
        external_services:
          custom_dashboards:
            enabled: true
          prometheus:
            url: http://lma-prometheus.lma:9090
          tracing:
            enabled: true
            namespace_selector: true
            url: http://jaeger-operator-jaeger-query.lma:16686
        istio_component_namespaces:
          prometheus: lma
        istio_namespace: istio-namespace1
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: service-mesh-resource
  name: service-mesh-resource
spec:
  chart:
    name: service-mesh-resource
    repository: https://openinfradev.github.io/hanu-helm-repo
    version: 0.1.2
  helmVersion: v3
  releaseName: service-mesh-resource
  targetNamespace: istio-system
  values:
    enabled: true
    istioNamespace: istio-namespace1
    meshConfig:
      enableAccessLog: true
      enableTracing: true
      sampling: 100
    profile: demo
    tracing_url: jaeger-operator-jaeger-collector.lma.svc:9411
