#!/usr/bin/python3
from common import Helm, Repos
import sys, getopt, yaml, os, time

TEMPDIR="tmp"

def template_yaml(manifests):
  for chart in manifests.keys():
    manifests[chart].generateSeperatedResources()


def load_manifest(manifest,target):
  os.system("awk '{f=\"split_\" NR; print $0 > f}' RS='---' "+manifest)

  manifests = dict()
  for entry in os.scandir():
    if entry.name.startswith('split_'):
      with open(entry, 'r') as stream:
        try:
          parsed = yaml.safe_load(stream)
          manifests[parsed['metadata']['name']]=Helm( 
            parsed['spec']['chart']['repository'],
            parsed['spec']['chart']['name'],
            parsed['spec']['releaseName'],
            parsed['spec']['targetNamespace'],
            parsed['spec']['chart']['version'],
            parsed['spec']['values'])
        except yaml.YAMLError as exc:
          print(exc)
  os.system("rm  split_*")

  return manifests

def printhelp():
    print('Usage: template -m APP_MANIFEST')

def main(argv):
  manifest=''
  wf='default'
  try:
    opts, args = getopt.getopt(argv,"hm:",["manifest="])
  except getopt.GetoptError:
    printhelp()
    sys.exit(-1)
  
  for opt, arg in opts:
    if opt == '-h':
      printhelp()
      sys.exit(0)
    elif opt in ("-m", "--manifest"):
      manifest = arg

  if (manifest==''):
    printhelp()
    sys.exit(-1)

  try:
    manifests=load_manifest(manifest, TEMPDIR)

    template_yaml(manifests)
  except yaml.YAMLError as exc:
    print(exc)


if __name__ == "__main__":
  main(sys.argv[1:])
  